name: Gitleaks scan via GHA

on:
    push:
     branches:
      - master
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Code
        run: echo "Compiling..."

      - name: Produce Binary
        run: sleep 5

      - name: Push binary
        run: echo "Pushing Binary to ECR..."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Scan with Gitleaks
        uses: cloudbees-io-gha/gitleaks-scan-publish@v1
     
          
          
         
